name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Setup test environment
        run: |
          php artisan key:generate
          # Zet database op SQLite voor tests
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=:memory:/' .env
          php artisan migrate --force

      - name: Run my specific tests only
        run: |
          php artisan test tests/Feature/DateFilterFeatureTest.php
          php artisan test tests/Unit/DateFilterUnitTest.php
          php artisan test tests/Feature/HeatmapFeatureTest.php
          php artisan test tests/Unit/HeatmapUnitTest.php
